services:
  docmost:
    container_name: docmost
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'https://wiki.matthewrwhalen.com'
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: 'postgresql://docmost:${DB_PASSWORD}@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3002:3000"
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUMES}/docmost/storage:/app/data/storage
    networks:
      caddy:
      docmost:
    labels:
      - "homepage.group=Other Services"
      - "homepage.name=Home Wiki"
      - "homepage.href=https://wiki.matthewrwhalen.com"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUMES}/docmost/db:/var/lib/postgresql/data
    networks: 
      docmost:

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUMES}/docmost/redis:/data
    networks:
      docmost:
      
networks:
  docmost:
    name: docmost
    driver: bridge
  caddy:
    external: true