services:
    caddy:
        container_name: caddy
        # image: caddy:latest
        env_file:
          - .env
          - ../.env
        build:
            context: .
            dockerfile: Dockerfile
        # publish everything you deem necessary
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
        networks:
            - caddy
        restart: unless-stopped
        volumes:
            - ./conf:/etc/caddy
            - ./site:/srv
            - ${DOCKER_VOLUMES}/caddy/data:/data
            - ${DOCKER_VOLUMES}/caddy/caddy_config:/config
        # dns:
        #   - 1.1.1.1
    wg-easy:
        image: ghcr.io/wg-easy/wg-easy:15
        container_name: wg-easy
        depends_on: [adguard, caddy]
        environment:
            - PORT=80
            - WG_HOST=${WG_HOST}
            - WG_DEFAULT_DNS=adguard #10.2.0.100
            - WG_PORT=51820
        volumes:
            - ${DOCKER_VOLUMES}/wg-easy:/etc/wireguard
            - /lib/modules:/lib/modules:ro
        ports:
            - "51820:51820/udp"
        networks:
            caddy:
            vpn-net:
                # ipv4_address: 10.2.0.3
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
            # - net.ipv6.conf.all.forwarding=1
        labels:
            - "homepage.group=Network Management"
            - "homepage.name=Wireguard"
            - "homepage.href=https://wg-easy.matthewrwhalen.com"
    adguard:
        image: adguard/adguardhome:v0.107.64
        depends_on: [caddy]
        container_name: adguard
        restart: unless-stopped
        volumes:
            - ${DOCKER_VOLUMES}/adguard/work:/opt/adguardhome/work
            - ${DOCKER_VOLUMES}/adguard/conf:/opt/adguardhome/conf
        ports:
            - "53:53/tcp"    
            - "53:53/udp"    
            # - 3000:3000/tcp
        networks:
            vpn-net:
                # ipv4_address: 10.2.0.100
            caddy:
        labels:
            - "homepage.group=Network Management"
            - "homepage.name=AdGuard Home"
            - "homepage.href=https://adguard.matthewrwhalen.com"

networks:
    caddy:
        name: caddy
        # enable_ipv6: true
        driver: bridge
        attachable: true
    vpn-net:
        name: vpn-net
        driver: bridge