services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    container_name: homepage
    ports:
      - 3001:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      caddy:
    environment:
      HOMEPAGE_ALLOWED_HOSTS: cleopatra:3001,localhost:3001,127.0.0.1:3001,internal.${DOMAIN_NAME},192.168.86.157:3001

networks:
  caddy:
    external: true